blank_issues_enabled: false
contact_links:
  - name: Twitch.me Support
    url: mailto:test.foxcat@gmail.com?subject=Online%20Support%F0%9F%98%8E&body=Your%20Error%3A%0D%0ADescription%3A
    about: Contact me if you're having trouble with the site.
